target: areamn.o area1.o area2.o area3.o
	cc -o target areamn.o area1.o area2.o area3.o
areamn.o: areamn.c
	cc -c areamn.c
area1.o: area1.c
	cc -c area1.c
area2.o: area2.c
	cc -c area2.c
area3.o: area3.c
	cc -c area3.c
