target:main.o strlen.o mstrcpy.o mstrcat.o cntvwls.o cntwords.o
	cc -o target main.o strlen.o mstrcpy.o mstrcat.o cntvwls.o cntwords.o
main.o: main.c mystr.h
	cc -c main.c 
strlen.o: strlen.c mystr.h
	cc -c strlen.c
mstrcpy.o: mstrcpy.c mystr.h
	cc -c mstrcpy.c
mstrcat.o: mstrcat.c mystr.h
	cc -c mstrcat.c
cntvwls.o: cntvwls.c mystr.h
	cc -c cntvwls.c
cntwords.o: cntwords.c mystr.h
	cc -c cntwords.c	
 
